cmake_minimum_required(VERSION 3.5)
project(Eikonal CXX)

# lib and bin will be in top source
set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}")
# set runtime path for shared libraries
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "7.5.0")
    message(FATAL_ERROR "Insufficient gcc version. Must be 7.5.0 or greater")
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
  set(BLA_VENDOR Intel10_64_dyn)
else()
  message(FATAL_ERROR "Compiler ID must be GNU or Intel")
endif()

find_package(OpenMP REQUIRED)
find_package(LAPACK REQUIRED)
find_package(BLAS REQUIRED)

# general compiler flags
option(debug "Build with debugger" OFF)

# setting include dir and general compile flags
# include dirs
include_directories(include)
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(NOT debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -Iinclude -O3 -march=native")
  elseif(debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Iinclude -O3 -g -DDEBUG -march=native")
  endif()
  include_directories(/usr/include)
  include_directories(/usr/include/openblas)
else()
  if(NOT debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -diag-disable remark -Iinclude -O3 -ipo -DUSE_MKL")
  elseif(debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Iinclude -g -DDEBUG -DUSE_MKL")
  endif()
  include_directories(${MKLROOT}/include)
endif()

# setting lib src files
set(sfactorSRC include/sFactors.h)
set(kmatSRC include/kMat.h)
set(dmatSRC include/dMat.h)
set(jpolySRC include/jPoly.h)
set(tensorquadSRC include/mapTensorQuad.h)
set(jweightSRC include/jWeight.h)
set(jmatSRC include/jMat.h)
set(jevdSRC include/jevd.h)
set(ngjquadSRC include/ngjquad.h)
set(legquadSRC include/legQuad.h)

# set build output paths
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

#building lib
add_library(sfactors SHARED ${sfactorSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${sfactorSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
target_link_libraries(sfactors gomp) 
#else()
  #set_source_files_properties(${sfactorSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
  #target_link_libraries(sfactors ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
#endif()

#add_library(kmat SHARED ${kmatSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${kmatSRC} PROPERTIES COMPILE_FLAGS "-fPIC")
#else()
#  set_source_files_properties(${kmatSRC} PROPERTIES COMPILE_FLAGS "-xHost -fpic")
#endif()
#
#add_library(dmat SHARED ${dmatSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${dmatSRC} PROPERTIES COMPILE_FLAGS "-fPIC")
#else()
#  set_source_files_properties(${dmatSRC} PROPERTIES COMPILE_FLAGS "-xHost -fpic ")
#endif()
#
#add_library(tensorquad SHARED ${tensorquadSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${tensorquadSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#  target_link_libraries(tensorquad gomp)
#else()
#  set_source_files_properties(${tensorquadSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic")
#  target_link_libraries(tensorquad ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
#endif()
#
#add_library(jpoly SHARED ${jpolySRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(jpoly sfactors) 
#
#add_library(jweight SHARED ${jweightSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${jweightSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${jweightSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(jweight tensorquad) 
#
#add_library(jmat SHARED ${jmatSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${jmatSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${jmatSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(jmat jpoly jweight) 
#
#add_library(jevd SHARED ${jevdSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${jevdSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${jevdSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(jevd gomp) 
#
#add_library(ngjquad SHARED ${ngjquadSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${ngjquadSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${ngjquadSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(ngjquad jmat) 
#
#add_library(legquad SHARED ${legquadSRC})
#if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#  set_source_files_properties(${legquadSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
#else()
#  set_source_files_properties(${legquadSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
#endif()
#target_link_libraries(legquad ngjquad) 



# install libs
install(TARGETS sfactors ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS kmat ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS dmat ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS jmat ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS jweight ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS jpoly ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS ngjquad ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS legquad ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS jevd ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#install(TARGETS tensorquad ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
#
