cmake_minimum_required(VERSION 3.0)
project(Eikonal CXX)

# lib and bin will be in top source
set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}")
# set runtime path for shared libraries
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "7.5.0")
    message(FATAL_ERROR "Insufficient gcc version. Must be 7.5.0 or greater")
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
  set(BLA_VENDOR Intel10_64_dyn)
else()
  message(FATAL_ERROR "Compiler ID must be GNU or Intel")
endif()

find_package(OpenMP REQUIRED)
find_package(LAPACK REQUIRED)
find_package(BLAS REQUIRED)

# general compiler flags
option(debug "Build with debugger" OFF)

# setting include dir and general compile flags
# include dirs
include_directories(include)
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(NOT debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -Iinclude -O3 -march=native")
  elseif(debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Iinclude -O3 -g -DDEBUG -march=native")
  endif()
  include_directories(/usr/include)
  include_directories(/usr/include/openblas)
else()
  if(NOT debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -diag-disable remark -Iinclude -O3 -ipo -DUSE_MKL")
  elseif(debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Iinclude -g -DDEBUG -DUSE_MKL")
  endif()
  include_directories(${MKLROOT}/include)
endif()

# setting lib src files
set(sfactorSRC include/sFactors.h)
set(kmatSRC include/kMat.h)
set(dmatSRC include/dMat.h)
set(jpolySRC include/jPoly.h)
set(tensorquadSRC include/mapTensorQuad.h)
set(jweightSRC include/jWeight.h)
set(jmatSRC include/jMat.h)
set(jevdSRC include/jevd.h)
set(ngjquadSRC include/ngjquad.h)
set(legquadSRC include/legQuad.h)

# set build output paths
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

#building lib
add_library(sfactors SHARED ${sfactorSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${sfactorSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
  target_link_libraries(sfactors gomp) 
else()
  set_source_files_properties(${sfactorSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
  target_link_libraries(sfactors ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
endif()

add_library(kmat SHARED ${kmatSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${kmatSRC} PROPERTIES COMPILE_FLAGS "-fPIC")
else()
  set_source_files_properties(${kmatSRC} PROPERTIES COMPILE_FLAGS "-xHost -fpic")
endif()

add_library(dmat SHARED ${dmatSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${dmatSRC} PROPERTIES COMPILE_FLAGS "-fPIC")
else()
  set_source_files_properties(${dmatSRC} PROPERTIES COMPILE_FLAGS "-xHost -fpic ")
endif()

add_library(tensorquad SHARED ${tensorquadSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${tensorquadSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
  target_link_libraries(tensorquad gomp)
else()
  set_source_files_properties(${tensorquadSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic")
  target_link_libraries(tensorquad ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
endif()

add_library(jpoly SHARED ${jpolySRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(jpoly sfactors) 

add_library(jweight SHARED ${jweightSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${jweightSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${jweightSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(jweight tensorquad) 

add_library(jpoly SHARED ${jpolySRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${jpolySRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(jmat jpoly jweight) 

add_library(jevd SHARED ${jevdSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${jevdSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${jevdSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(jevd gomp) 

add_library(ngjquad SHARED ${ngjquadSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${ngjquadSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${ngjquadSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(ngjquad jmat) 


add_library(particles SHARED ${particlesSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${particlesSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${particlesSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(particles grid cheb)

add_library(spreadInterp SHARED ${spreadInterpSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${spreadInterpSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
else()
  set_source_files_properties(${spreadInterpSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
endif()
target_link_libraries(spreadInterp particles)

add_library(spreadInterpDerivX SHARED ${spreadInterpSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_target_properties(spreadInterpDerivX PROPERTIES COMPILE_FLAGS "-DTORQUE_X -fPIC -fopenmp")
else()
  set_target_properties(spreadInterpDerivX PROPERTIES COMPILE_FLAGS "-xHost -DTORQUE_X -qopenmp -fpic")
endif()
target_link_libraries(spreadInterpDerivX particles)

add_library(spreadInterpDerivY SHARED ${spreadInterpSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_target_properties(spreadInterpDerivY PROPERTIES COMPILE_FLAGS "-DTORQUE_Y -fPIC -fopenmp")
else()
  set_target_properties(spreadInterpDerivY PROPERTIES COMPILE_FLAGS "-xHost -DTORQUE_Y -qopenmp -fpic")
endif()
target_link_libraries(spreadInterpDerivY particles)

add_library(spreadInterpDerivZ SHARED ${spreadInterpSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_target_properties(spreadInterpDerivZ PROPERTIES COMPILE_FLAGS "-DTORQUE_Z -fPIC -fopenmp")
else()
  set_target_properties(spreadInterpDerivZ PROPERTIES COMPILE_FLAGS "-xHost -DTORQUE_Z -qopenmp -fpic")
endif()
target_link_libraries(spreadInterpDerivZ particles)

add_library(transform SHARED ${transformSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${transformSRC} PROPERTIES COMPILE_FLAGS "-lfftw3_omp -lfftw3 -lm -fopenmp -fPIC ")
  target_link_libraries(transform fftw3_omp fftw3 gomp)
else()
  set_source_files_properties(${transformSRC} PROPERTIES COMPILE_FLAGS "-xHost -lfftw3_omp -lfftw3 -qopenmp -fpic ")
  target_link_libraries(transform ${fftw3_omp} ${fftw3} ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
endif()

add_library(linSolve SHARED ${linSolveSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${linSolveSRC} PROPERTIES COMPILE_FLAGS " -lm -lblas -llapacke -DHAVE_LAPACK_CONFIG_H -DLAPACK_COMPLEX_STRUCTURE -lfftw3 -fopenmp -fPIC")
  target_link_libraries(linSolve gomp openblas lapack lapacke fftw3)
else()
  set_source_files_properties(${linSolveSRC} PROPERTIES COMPILE_FLAGS "-lmkl_rt -Wl,--no-as-needed -lpthread -ldl -qopenmp -lfftw3 -fpic")
  target_link_libraries(linSolve ${BLAS_mkl_rt_LIBRARY} ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY} ${fftw3})
endif()

add_library(dpTools SHARED ${dpToolsSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${dpToolsSRC} PROPERTIES COMPILE_FLAGS " -lm -lblas -llapacke -DHAVE_LAPACK_CONFIG_H -DLAPACK_COMPLEX_STRUCTURE -fopenmp -lfftw3_omp -lfftw3 -fPIC")
  target_link_libraries(dpTools linSolve fftw3_omp)
else()
  set_source_files_properties(${dpToolsSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -lfftw3 -fpic")
  target_link_libraries(dpTools linSolve)
endif()


add_library(BC SHARED ${bcSRC})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set_source_files_properties(${bcSRC} PROPERTIES COMPILE_FLAGS "-fPIC -fopenmp")
  target_link_libraries(BC gomp)
else()
  set_source_files_properties(${bcSRC} PROPERTIES COMPILE_FLAGS "-xHost -qopenmp -fpic ")
  target_link_libraries(BC ${OpenMP_iomp5_LIBRARY} ${OpenMP_pthread_LIBRARY})
endif()
# install libs
install(TARGETS spreadInterp ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS spreadInterpDerivX ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS spreadInterpDerivY ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS spreadInterpDerivZ ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS cheb ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS grid ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS particles ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS transform ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS linSolve ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS dpTools ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS BC ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
# add env config script to examples dir
configure_file(cmake.in/cpuconfig.sh.in ${CMAKE_INSTALL_PREFIX}/examples/cpuconfig.sh @ONLY)
